name: Build

on:
  push:
    tags:
    - 'latest'
    - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
      
      - name: Build sln
        run: dotnet build --configuration Release

      - name: Publish GenerateNotice tool
        run: dotnet publish --configuration Release ./src/GenerateNotice/GenerateNotice.csproj
      
      - name: Build GenerateNotice package
        run: dotnet build --configuration Release ./src/GenerateNotice.Nuget/nuget.proj

      - name: Upload GenerateNotice package
        uses: actions/upload-artifact@v3
        with:
          name: GenerateNotice-package
          path: ./src/GenerateNotice.Nuget/*.nupkg
          if-no-files-found: error

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: bicep-nupkg-any
          path: out/*
          if-no-files-found: error

      - name: Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: dotnet