name: Build

on:
  push:
    tags:
    - 'latest'
    - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Initialize CodeQL
        uses: github/codeql-action/init@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          languages: csharp

      - name: Setup .NET Core
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      
      - name: Build sln
        run: dotnet build --configuration Release

      - name: Publish GenerateNotice tool
        run: dotnet publish --configuration Release ./src/GenerateNotice/GenerateNotice.csproj
      
      - name: Build GenerateNotice package
        run: dotnet build --configuration Release ./src/GenerateNotice.Nuget/nuget.proj

      - name: Upload GenerateNotice package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: GenerateNotice-package
          path: ./src/GenerateNotice.Nuget/*.nupkg
          if-no-files-found: error

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Upload Packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bicep-nupkg-any
          path: out/*
          if-no-files-found: error

      - name: Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings

      - name: Upload Code Coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: dotnet

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1